apiVersion: v2
name: ilum-marquez
description: Marquez packaged by Ilum, an open source metadata service for the collection, aggregation, and visualization of a data ecosystem's metadata.
home: https://ilum.cloud/
icon: https://ilum.cloud/icons/android-chrome-512x512.png
keywords:
  - metadata
  - data-catalog
  - data-discovery
  - data-dictionary
  - data-governance
  - data-lineage
  - data-ops
  - data-provenance
  - metadata-service
  - marquez
  - data-ecosystem-metadata
sources:
  - https://github.com/ilum-cloud/marquez
  - https://ilum.cloud/
version: 0.53.1

annotations:
  artifacthub.io/prerelease: "false"

dependencies:
  - condition: postgresql.enabled
    name: postgresql
    repository: https://charts.bitnami.com/bitnami
    version: ^13.x
