{{- if .Values.web.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "ilum-marquez.fullname" . }}-web
  labels:
    {{- include "ilum-marquez.labels" . | nindent 4 }}
    app: ilum-marquez-web
  {{- if .Values.commonAnnotations }}
  annotations:
    {{- toYaml .Values.commonAnnotations | nindent 4 }}
  {{- end }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ilum-marquez-web
  template:
    metadata:
      labels:
        {{- include "ilum-marquez.labels" . | nindent 8 }}
        app: ilum-marquez-web
    spec:
      {{- with .Values.web.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with include "ilum-marquez-web.imagePullSecrets" . }}
      imagePullSecrets:
        {{- . | nindent 8 }}
      {{- end }}
      containers:
        - name: ilum-marquez-web
          {{- with .Values.web.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          image: "{{ .Values.web.image.registry }}/{{ .Values.web.image.repository }}:{{ .Values.web.image.tag }}"
          imagePullPolicy: {{ .Values.web.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.web.service.port }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /healthcheck
              port: http
          readinessProbe:
            httpGet:
              path: /healthcheck
              port: http
          env:
            - name: WEB_PORT
              value: {{ .Values.web.service.port | quote }}
            - name: MARQUEZ_HOST
              value: {{ include "ilum-marquez.fullname" . }}
            - name: MARQUEZ_PORT
              value: {{ .Values.marquez.service.port | quote }}
          {{- if .Values.web.resources }}
          resources: {{- toYaml .Values.web.resources | nindent 12 }}
          {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
