apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "ilum-marquez.fullname" . }}
  labels:
    {{- include "ilum-marquez.labels" . | nindent 4 }}
  {{- if .Values.commonAnnotations }}
  annotations:
    {{- toYaml .Values.commonAnnotations | nindent 4 }}
  {{- end }}
spec:
  replicas: {{ .Values.marquez.replicaCount }}
  selector:
    matchLabels:
      app: ilum-marquez
  template:
    metadata:
      labels:
        {{- include "ilum-marquez.labels" . | nindent 8 }}
        app: ilum-marquez
      {{- if .Values.marquez.podAnnotations }}
      annotations:
        {{- toYaml .Values.marquez.podAnnotations | nindent 8 }}
      {{- end }}
    spec:
      {{- with .Values.marquez.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if .Values.serviceAccount.create }}
      serviceAccountName: {{ include "ilum-marquez.serviceAccountName" . }}
      {{- end }}
      {{- with include "ilum-marquez.imagePullSecrets" . }}
      imagePullSecrets:
        {{- . | nindent 8 }}
      {{- end }}
      initContainers:
        {{- if .Values.postgresql.enabled }}
        - name: wait-for-db
          image: {{ .Values.marquez.db.image }} 
          imagePullPolicy: IfNotPresent
          command:
            - /bin/bash
          args:
            - -ec
            - |
              until pg_isready -h ${POSTGRES_HOST} -p ${POSTGRES_PORT} -U ${POSTGRES_USER}; do
                echo "Waiting for PostgreSQL server to be ready..."
                sleep 2
              done
          env:
            - name: POSTGRES_HOST
              value: {{ printf "%s-%s" .Release.Name "postgresql" | trunc 63 | trimSuffix "-" }}
            - name: POSTGRES_PORT
              value: "5432"
            - name: POSTGRES_USER
              value: {{ .Values.postgresql.auth.username | quote }}
        {{- else }}
        - name: wait-for-db
          image: {{ .Values.marquez.db.image }}
          imagePullPolicy: IfNotPresent
          command:
            - /bin/bash
          args:
            - -ec
            - |
              until pg_isready -h ${POSTGRES_HOST} -p ${POSTGRES_PORT} -U ${POSTGRES_USER} -d ${POSTGRES_DB}; do
                echo "Waiting for PostgreSQL server to be ready..."
                sleep 2
              done
              until psql -h ${POSTGRES_HOST} -p ${POSTGRES_PORT} -U ${POSTGRES_USER} -d ${POSTGRES_DB} -c "SELECT 1" > /dev/null 2>&1; do
                echo "Waiting for database ${POSTGRES_DB} to be created..."
                sleep 2
              done
              echo "Database ${POSTGRES_DB} is ready!"
          env:
            - name: POSTGRES_HOST
              value: {{ .Values.marquez.db.host | quote }}
            - name: POSTGRES_PORT
              value: {{ .Values.marquez.db.port | quote }}
            - name: POSTGRES_USER
              value: {{ .Values.marquez.db.user | quote }}
            - name: PGPASSWORD
              value: {{ .Values.marquez.db.password | quote }}
            - name: POSTGRES_DB
              value: {{ .Values.marquez.db.name | quote }}
        {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          {{- with .Values.marquez.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          image: "{{ .Values.marquez.image.registry }}/{{ .Values.marquez.image.repository }}:{{ .Values.marquez.image.tag }}"
          imagePullPolicy: {{ .Values.marquez.image.pullPolicy }}
          volumeMounts:
            - name: marquez-volume
              mountPath: /usr/src/app/config.yml
              subPath: config.yml
          ports:
            - name: http
              containerPort: 5000
              protocol: TCP
            - name: http-admin
              containerPort: 5001
              protocol: TCP
          {{- with .Values.marquez.livenessProbe }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.marquez.readinessProbe }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          env:
            - name: MARQUEZ_PORT
              value: {{ 5000 | quote }}
            - name: MARQUEZ_ADMIN_PORT
              value: {{ 5001 | quote }}
            - name: MARQUEZ_CONFIG
              value: /usr/src/app/config.yml
            - name: POSTGRES_HOST
              value: {{ if .Values.postgresql.enabled }}{{ printf "%s-%s" .Release.Name "postgresql" | trunc 63 | trimSuffix "-" }}{{ else }}{{ .Values.marquez.db.host | quote }}{{ end }}
            - name: POSTGRES_PORT
              value: {{ if .Values.postgresql.enabled }}{{ "5432" | quote }}{{ else }}{{ .Values.marquez.db.port | quote }}{{ end }}
            - name: POSTGRES_DB
              value: {{ if .Values.postgresql.enabled }}{{ .Values.postgresql.auth.database | quote }}{{ else }}{{ .Values.marquez.db.name | quote }}{{ end }}
            - name: POSTGRES_USER
              value: {{ if .Values.postgresql.enabled }}{{ .Values.postgresql.auth.username | quote }}{{ else }}{{ .Values.marquez.db.user | quote }}{{ end }}
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  {{- if .Values.marquez.existingSecretName }}
                  name: {{ .Values.marquez.existingSecretName }}
                  key: marquez-db-password
                  {{- else if .Values.postgresql.enabled }}
                  name: {{ printf "%s-%s" .Release.Name "postgresql" | trunc 63 | trimSuffix "-" }}
                  key: password
                  {{- else }}
                  name: {{ include "ilum-marquez.fullname" . }}
                  key: marquez-db-password
                  {{- end }}
            - name: MIGRATE_ON_STARTUP
              value: {{ .Values.marquez.migrateOnStartup | quote }}
          {{- if .Values.marquez.resources }}
          resources: {{- toYaml .Values.marquez.resources | nindent 12 }}
          {{- end }}
        {{- with .Values.marquez.extraContainers }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      volumes:
        - name: marquez-volume
          configMap:
            name: {{ include "ilum-marquez.fullname" . }}-config
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
