{{- if not .Values.marquez.existingSecretName }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ilum-marquez.fullname" . }}
  labels:
    {{- include "ilum-marquez.labels" . | nindent 4 }}
  {{- with .Values.secret.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
type: Opaque
data:
  {{- if .Values.marquez.db.password }}
  marquez-db-password: {{ .Values.marquez.db.password | b64enc | quote }}
  {{ else }}
  marquez-db-password: {{ required "A Marquez DB Password is required!" .Values.marquez.db.password }}
  {{- end }}
{{- end }}
