apiVersion: v1
kind: Service
metadata:
  name: {{ include "ilum-marquez.fullname" . }}
  labels:
    {{- include "ilum-marquez.labels" . | nindent 4 }}
  {{- with .Values.marquez.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.marquez.service.type }}
  {{- if and (eq .Values.marquez.service.type "ClusterIP") .Values.marquez.service.clusterIP }}
  clusterIP: {{ .Values.marquez.service.clusterIP }}
  {{- end }}
  {{- if and (eq .Values.marquez.service.type "LoadBalancer") .Values.marquez.service.loadBalancerIP }}
  loadBalancerIP: {{ .Values.marquez.service.loadBalancerIP }}
  {{- end }}
  ports:
    - name: http
      port: {{ .Values.marquez.service.port }}
      targetPort: http
      {{- if and (or (eq .Values.marquez.service.type "LoadBalancer") (eq .Values.marquez.service.type "NodePort")) .Values.marquez.service.nodePort }}
      nodePort: {{ .Values.marquez.service.nodePort }}
      {{- end }}
  selector:
    {{- include "ilum-marquez.selectorLabels" . | nindent 4 }}
    app: ilum-marquez
